version: '3.8'

services:
  app:
    build: .
    container_name: go-auth-service
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${MYSQL}
      - SECRET_KEY=${SECRET_KEY}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET_KEY=${GOOGLE_CLIENT_SECRET_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET_KEY=${GITHUB_CLIENT_SECRET_KEY}
      - GEMINI_API=${GEMINI_API}
      - GEMINI_URL=${GEMINI_URL}
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: goauthdb
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
